### ISSUE TITLE
Inhalt

### ISSUE THREAD

**Issue by StephanWagener** [frozenyogurt/WAB_App#16]
einige news befüllen, portrait texte, weiterbildung, warum hftl, services, faq, mitarbeiter, kontakt und die Fragen des Tests

**Comment by frozenyogurt** [comment]
Assigne ich mir auch. Werde dich dann nach den Studieninhalten dazu anrufen.

**Comment by frozenyogurt** [comment]
Folgende Themen schicke ich dir gleich per Mail und sind somit abgehakt: News, Portrait, FAQ, Mitarbeiter, der fehlende Reiter "Labore" bei Services und die Fragen des Tests

Offene Themen sind: Weiterbildung, Warum HfTL

Dafür mache ich jeweils einen extra Issue auf, um die Übersicht zu behalten und schließe diesen.
