### ISSUE TITLE
niedrige Prio: Text ändert sich nicht sofort bei Sprachänderung

### ISSUE THREAD

**Issue by frozenyogurt** [frozenyogurt/WAB_App#18]
Wenn man sich einen Text anguckt, dann ins Menü geht, die Sprache ändert, speichert und zurück geht, dann wird immer noch der Text in der ursprünglichen Sprache angezeigt.
Erst-User könnten denken es gibt keine Übersetzung oder es funktioniert nicht.
Denn erst bei erneutem Laden der "Seite" wird der Text in der ausgewählten Sprache angezeigt.
Kann man als Feature beheben, muss aber nicht unbedingt wenn es sehr viel Aufwand ist.

**Comment by StephanWagener** [comment]
fertig
