### ISSUE TITLE
Studienordnung und curriculum

### ISSUE THREAD

**Issue by StephanWagener** [frozenyogurt/WAB_App#30]
Die Inhalt passen überhaupt nicht. Hier sollten auch die Credits, die Dauer, Beginn, Kosten etc. stehen. Vielleicht könnte ich hier eine Listenansicht einfügen, in die wir das packen.

**Comment by StephanWagener** [comment]
Überschrift zum ersten Text des Studiengangs
Link zur Website
Tabellarische Ansicht für die Studiengänge

**Comment by StephanWagener** [comment]
fehlen nur noch die Texte

**Comment by frozenyogurt** [comment]
Glaube die aktuelle Version ist gut. Bitte schließ das, wenn du damit einverstanden bist, @StephanWagener

**Comment by StephanWagener** [comment]
Ja ich behebe noch den Fehler beim ausblenden und dann ist gut.
