### ISSUE TITLE
Name der App 

### ISSUE THREAD

**Issue by StephanWagener** [frozenyogurt/WAB_App#32]
Also hftl_app ist nicht optimal

**Comment by frozenyogurt** [comment]
Nur "HfTL" ist gut, da unsere Hochschule meines Wissens nach keine weitere App hat.

**Comment by frozenyogurt** [comment]
Magst du das kurz ändern @StephanWagener falls @fhollas auch nichts besseres einfällt? Danach bitte close :)

**Comment by frozenyogurt** [comment]
Und wenn wir schon bei Namen sind: Finde "Duales Studium" klingt besser als "Dualstudium".

**Comment by fhollas** [comment]
da stimme ich Simi zu. Und HfTL reicht als Name auch aus.

**Comment by StephanWagener** [comment]
Okay dann passt das bitte in den string.xml Dateien an

**Comment by frozenyogurt** [comment]
Done in der Deutschen. Die Kacheln musst du aber selbst machen.

**Comment by StephanWagener** [comment]
Was meinst du bei den Kacheln das Design ?

**Comment by frozenyogurt** [comment]
Nevermind, ist schon erledigt. ;)
