### ISSUE TITLE
Barrierefreiheit

### ISSUE THREAD

**Issue by frozenyogurt** [frozenyogurt/WAB_App#33]
Wäre es möglich ohne großen Aufwand eine Checkbox in den Einstellungen zu implementieren, die als Auswirkung hat, dass die Schrift generell um 4px (Wert kann man testen) größer wird?
Dann könnten wir die App auch als Barrierefrei deklarieren.
Wenn nicht, bitte close.

**Comment by StephanWagener** [comment]
erledigt.
