### ISSUE TITLE
Optionen/Einstellungen

### ISSUE THREAD

**Issue by frozenyogurt** [frozenyogurt/WAB_App#37]
Statt Farbstil oder ähnlichem steht in den Einstellungen zwei mal Textgröße.

**Comment by frozenyogurt** [comment]
Bei "Zurücksetzen" wird die wirkliche Textgröße nicht auf Mittel zurückgesetzt.

**Comment by StephanWagener** [comment]
ja stimmt... ich kümmere mich drum

**Comment by StephanWagener** [comment]
behoben
