### ISSUE TITLE
Padding bei Weiterbildungen

### ISSUE THREAD

**Issue by frozenyogurt** [frozenyogurt/WAB_App#38]
Da ist der Abstand unten zum Bildschirmende kleiner als bei allen anderen Punkten. Sieht so aus als käme noch etwas.

**Comment by frozenyogurt** [comment]
TOEIC um genau zu sein.

**Comment by StephanWagener** [comment]
okay guck ich mir auch an

**Comment by StephanWagener** [comment]
fertig
