### ISSUE TITLE
Fehlende Tags in der String.xml -> Übersetzung nicht möglich

### ISSUE THREAD

**Issue by fhollas** [frozenyogurt/WAB_App#40]
Ein paar Textbausteine sind in den string Dateien nicht enthalten, weder der deutschen noch der englischen. 
z.B. die "Berufliche Perspektiven" Überschrift in der Beschreibung der Studiengänge. Ich glaube bei der Bibliothek ist auch noch so eine Überchrift, hab ich aber nicht mehr genau im Kopf.

**Comment by StephanWagener** [comment]
guck ich mir an

**Comment by StephanWagener** [comment]
behoben
