### ISSUE TITLE
Studiengangtest

### ISSUE THREAD

**Issue by frozenyogurt** [frozenyogurt/WAB_App#5]

**Comment by StephanWagener** [comment]
ich denke ich baue hierzu einen ViewPager mit den verschieden Fragen.

**Comment by StephanWagener** [comment]
ich behebe noch die Fehler bei der Auswertung und dann passt das

**Comment by StephanWagener** [comment]
ich versuche mal eine neue Auswertungsansicht zu erstellen

**Comment by StephanWagener** [comment]
ich denke die Optik und der Aufbau passt

**Comment by StephanWagener** [comment]
Jetzt ist die Funktionalität auch berichtigt worden. Eigentlich fertig der Test.
